import type { NextPage } from "next";

import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Our-Survey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>홈 페이지 입니다</div>
    </div>
  );
};

export default Home;
