import type { NextPage } from 'next';
import { type GetServerSideProps } from 'next';
import Head from 'next/head';
import { withAuth } from 'utills/isLoggedIn';

export const getServerSideProps: GetServerSideProps = withAuth(() => {
  return {
    props: {},
  };
});

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Our-Survey - 설문하는 사람들의 품앗이 공간</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>홈 페이지 입니다</div>
    </div>
  );
};

export default Home;
